global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using HarmonyLib;
global using SML;
global using UnityEngine;
global using Witchcraft.Utils;
global using static SML.Mod;
global using SRandom = System.Random;
global using UObject = UnityEngine.Object;
global using URandom = UnityEngine.Random;